# Generated by Django 3.0.7 on 2020-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201126_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
